DOCSTOOLS-884 and new mode for inclusions
yandex-cloud/yfm-docs pull request #108
Opened 2021-12-01 13:47 UTC by yndx-birman

2021-12-02 11:13 UTC, gorgeousvlad commented on package.json
> +    "yaml-front-matter": "^4.1.1",
он точно нужен не только в две зависимостях?

2021-12-02 11:44 UTC, yndx-birman commented on package.json
> +    "yaml-front-matter": "^4.1.1",
перенес в dev

2021-12-06 09:14 UTC, gorgeousvlad requested changes

2021-12-06 09:14 UTC, gorgeousvlad commented on src/services/tocs.ts
> +            const fileContent = readFileSync(from, 'utf8');
мы много файлов читаем в синхронном режиме?

2021-12-06 09:14 UTC, gorgeousvlad commented on src/services/tocs.ts
> +        if (item.items) {
`item.items` - легко запутаться в структуре объекта

2021-12-06 09:14 UTC, gorgeousvlad commented on src/models.ts
> +    addSourcePath?: boolean;
нигде не нашел описания этого параметра, за что он отвечает

2021-12-07 11:41 UTC, yndx-birman commented on src/services/tocs.ts
> +            const fileContent = readFileSync(from, 'utf8');
Здесь может быть много, зависит от размера toc.yaml, который инклудится

2021-12-07 11:47 UTC, yndx-birman commented on src/models.ts
> +    addSourcePath?: boolean;
Одно оглавление можно включать в другое https://ydocs.tech/ru/project/toc#includes
При этом меняется структура проекта, файлы лежащие с включаемым разделом переносятся в директорию главным оглавлением
При переносе, таким файлам в meta добавляется путь до исходника

Сам параметр addSourcePath  внутренний, про sourcePath нужно будет описать в документации в разделе включения оглавления https://ydocs.tech/ru/project/toc#includes

2021-12-08 14:11 UTC, gorgeousvlad commented on src/services/tocs.ts
> +            const fileContent = readFileSync(from, 'utf8');
может подумать про асихнронное чтение тогда?

2021-12-08 14:49 UTC, gorgeousvlad approved these changes

2021-12-08 14:55 UTC, merged