Debug through ts-node
yandex-cloud/yfm-docs pull request #224
Opened 2022-12-19 15:34 UTC by amosov-f

Ability to debug source .ts code through ts-node

2022-12-19 15:40 UTC, amosov-f commented on src/resolvers/md2html.ts
> -    const {conditionsInCode} = ArgvService.getConfig();
такой проперти просто нет у YfmArgv

2022-12-19 16:06 UTC, yndx-birman requested changes

2022-12-19 16:06 UTC, yndx-birman commented on src/services/contributors.ts
> +    if (!inputFolderPathLength) {
fileContent and inputFolderPathLength should be required in FileData
These errors will never be thrown

2022-12-19 16:06 UTC, yndx-birman commented on src/resolvers/md2html.ts
> -    const {conditionsInCode} = ArgvService.getConfig();
Look at the description of `conditionsInCode` in the settings https://ydocs.tech/en/settings

2022-12-19 16:07 UTC, moki commented on src/resolvers/md2html.ts
> -    const {conditionsInCode} = ArgvService.getConfig();
отсутсвие типа

нужно расширить

2022-12-19 16:08 UTC, moki commented on src/services/contributors.ts
> +    if (!inputFolderPathLength) {
https://github.com/yandex-cloud/yfm-docs/blob/0b5c6b492234c081566934e1c2fa36ec92b08715/src/models.ts

сделать обязательным тут

2022-12-19 17:26 UTC, amosov-f commented on src/resolvers/md2html.ts
> -    const {conditionsInCode} = ArgvService.getConfig();
fixed

2022-12-19 17:27 UTC, amosov-f commented on src/services/contributors.ts
> +    if (!inputFolderPathLength) {
fixed

2022-12-20 10:36 UTC, yndx-birman approved these changes

2022-12-20 13:16 UTC, merged