feat: add schema table
yandex-cloud/yfm-docs pull request #229
Opened 2022-12-26 14:02 UTC by amosov-f

2022-12-30 16:17 UTC, amosov-f commented on src/packages/credentials/yandex-oauth.ts
> +        logger.error('', error);
was compilation error

2023-01-10 12:20 UTC, moki requested changes
at least minor changes that i mentioned needed

also please clean up commit history(local rebase with squash) with appropriate commit message(feat(includers/openapi): ... )

2023-01-10 12:57 UTC, amosov-f commented on src/packages/credentials/yandex-oauth.ts
> +        logger.error('', error);
reverted

2023-01-10 12:57 UTC, amosov-f commented on src/services/includers/batteries/openapi/constants.ts
> +const PATH_PARAMS_SECTION_NAME = 'Path params';
fixed

2023-01-10 12:57 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/common.ts
> +function escape(cellContent: string) {
fixed

2023-01-10 12:57 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    PATH_PARAMS_SECTION_NAME, QUERY_PARAMS_SECTION_NAME,
fixed

2023-01-10 12:58 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +        data.description?.length && block([body(data.description)]),
fixed

2023-01-10 14:13 UTC, moki requested changes

2023-01-10 14:19 UTC, moki requested changes

2023-01-10 14:19 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return `<a href='#${ref.toLowerCase()}'>${ref}</a>`;
slugify href

https://github.com/yandex-cloud/yfm-docs/blob/c53392171534d7089a00605664815baf2243bcdb/src/services/includers/batteries/openapi/parsers.ts#L75

2023-01-10 14:34 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +        resp.schemas?.length && block(resp.schemas.map((s) => openapiBody(allRefs, visited, s))),
fixed

2023-01-10 14:34 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    for (const [k, v] of Object.entries(allRefs)) {
flxed

2023-01-10 14:35 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    Object.entries(merged.properties || {}).forEach(([key, v]) => {
fixed

2023-01-10 15:22 UTC, moki approved these changes

2023-01-10 15:26 UTC, merged