feat(includers/openapi): add sandbox plugin
yandex-cloud/yfm-docs pull request #249
Opened 2023-01-16 02:04 UTC by zorox112-practicum

<img width="1288" alt="Screenshot 2023-01-16 at 05 04 03" src="https://user-images.githubusercontent.com/112015178/212583261-5397f532-a094-4202-987f-d1edd5396f61.png">

2023-01-16 02:07 UTC, zorox112-practicum commented on src/app/components/App/App.tsx
> +import '@gravity-ui/uikit/build/esm/components/Loader/Loader.css';
Пришлось притащить @gravity-ui сюда, что крайне тупо, на сколько я понимаю по коду, то нужен просто еще один импорт в эти библиотеку в этот файл? (смутило, что не увидел аналогичных импортов)

https://github.com/yandex-cloud/docs-components/blob/ac3668268fbc3f4952e779019dbec48524a981b7/styles/yfm.scss#L3-L2

2023-01-16 21:11 UTC, yndx-birman commented on src/app/components/App/App.tsx
> +import '@gravity-ui/uikit/build/esm/components/Loader/Loader.css';
Вот здесь подключаются стили для тем https://github.com/yandex-cloud/yfm-docs/blob/94bb3e99ec64d557dab6e5f83656a728def9403b/src/app/components/App/App.tsx#L17
В темах есть импорт стилей для всех компонентов @gravity-ui/uikit https://github.com/yandex-cloud/docs-components/blob/master/styles/themes.scss#L1

Ты скинул ссылку на старую ревизию docs-components, где подключен @yandex-cloud/uikit
Разницы вроде быть не должно, но попробуй обновить docs-components в yfm-docs, если они старой версии
Тащить @gravity-ui/uikit отдельно правда не нужно

2023-01-16 21:13 UTC, yndx-birman commented
По визуальной части: кнопка send на всю ширину контента, может ее стоит ограничить по ширине текста в кнопке?

2023-01-16 21:16 UTC, yndx-birman commented on src/constants.ts
> +import openapiSandbox from './services/includers/batteries/openapi/plugin';
Можешь перенести импорт после импорта плагинов из @doc-tools/transform?

2023-01-24 11:26 UTC, moki commented on src/services/includers/batteries/openapi/plugin/utils.ts
> +    return `(function() {const rootContainer = document.querySelector('[id=&quot;${containerId}&quot;]');
@zorox112-practicum 

This might work on static html build, but for sure wouldn't work inside the viewer app, **CSP would not allow it**.

2023-01-24 11:36 UTC, moki requested changes
I recommend you to check out how code block plugin is doing it

dynamic javascript
https://github.com/yandex-cloud/yfm-transform/blob/master/src/js/code.ts

code for plugin itself
https://github.com/yandex-cloud/yfm-transform/blob/master/src/transform/plugins/code.ts

Therefore you'll have two additional exports inside your plugin plugin/js plugin/css and import them inside application
https://github.com/yandex-cloud/yfm-docs/blob/master/src/app/components/App/App.tsx

2023-02-06 12:32 UTC, yndx-birman commented on src/services/includers/batteries/openapi/plugin/public/sandbox.scss
> +.yfm-sandbox-column {
https://en.bem.info/methodology/naming-convention/#naming-rules

`.yfm-sandbox-column` => `.yfm-sandbox__column`
or better
```
.yfm-sandbox {
    &__column {
    }
}
```

2023-02-06 12:32 UTC, yndx-birman commented on src/services/includers/batteries/openapi/plugin/public/components/Error.tsx
> +                className="yfm-sandbox-card-text"
We use `bem-cn-lite` package to construct class names https://www.npmjs.com/package/bem-cn-lite

2023-02-06 16:04 UTC, yndx-birman commented on src/services/includers/batteries/openapi/plugin/constants.ts
> +export const yfmSandbox = block('yfm-sandbox');
`yfmSandbox` => `yfmSandboxBlock`

2023-02-06 17:18 UTC, 3y3 approved these changes

2023-02-06 17:30 UTC, moki approved these changes

2023-02-06 17:31 UTC, yndx-birman approved these changes

2023-02-07 09:03 UTC, merged