fix(includers/openapi): excess properties in allOf
yandex-cloud/yfm-docs pull request #270
Opened 2023-01-26 11:33 UTC by amosov-f

allOf merge bug: mutation of source schema lead to excess properties of objects

2023-01-26 16:53 UTC, moki requested changes
in function: [`prepareSampleElement`](https://github.com/yandex-cloud/yfm-docs/blob/b8c6dbd6dc6b1d6d096b93c7e387cbee0491abde/src/services/includers/batteries/openapi/generators/traverse.ts#L106)

`callstack: JSONSchema6[]`

also please come up with an adequate type for the function return value

2023-01-26 18:06 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/traverse.ts
>  export function prepareSampleObject(schema: JSONSchema6, callstack: any[] = []) {
this pull request is not about it
suggest fix it in separate pull request

2023-01-26 18:06 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/traverse.ts
>      const result: { [key: string]: any } = {};
this pull request is not about it
suggest to fix it in separate pull request

2023-01-27 15:26 UTC, 3y3 approved these changes

2023-01-30 12:56 UTC, merged