fix(includers/openapi): default value in query
yandex-cloud/yfm-docs pull request #272
Opened 2023-01-26 13:42 UTC by amosov-f

fix undefiened & default values

![Снимок экрана 2023-01-26 в 16 42 32](https://user-images.githubusercontent.com/3672471/214850292-3a87672d-f362-4ab8-9f7d-3532d0b1100d.png)

2023-01-26 19:15 UTC, moki requested changes

2023-01-26 19:15 UTC, moki commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    if (param.example !== undefined) {
why not `param.example != null` why should we render:

```
`Example: \`${null}\``
```

2023-01-26 19:15 UTC, moki commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    if (param.default !== undefined) {
why not `param.default != null` why should we render:

```
`Example: \`${null}\``
```

2023-01-26 19:15 UTC, moki commented on src/services/includers/batteries/openapi/types.ts
> +    example?: string | number | boolean;
would love separate type for that, that will signal about what kind of data we support

2023-01-26 19:15 UTC, moki commented on src/services/includers/batteries/openapi/types.ts
> +    default?: string | number | boolean;
same here

2023-01-26 19:30 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +export function concatNewLine(prefix: string, suffix: string) {
if its used somewhere else factor it out to `common` module

2023-01-27 10:37 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    if (param.example !== undefined) {
null is valid default value

2023-01-27 10:37 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    if (param.default !== undefined) {
null is valid default value

2023-01-27 10:52 UTC, amosov-f commented on src/services/includers/batteries/openapi/types.ts
> +    example?: string | number | boolean;
fixed

2023-01-27 10:52 UTC, amosov-f commented on src/services/includers/batteries/openapi/types.ts
> +    default?: string | number | boolean;
fixed

2023-01-27 10:52 UTC, amosov-f commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +export function concatNewLine(prefix: string, suffix: string) {
fixed

2023-01-27 15:29 UTC, 3y3 approved these changes

2023-01-30 17:46 UTC, moki approved these changes

2023-01-30 17:46 UTC, merged