Fixes
yandex-cloud/yfm-docs pull request #300
Opened 2023-03-01 12:23 UTC by zorox112-practicum

replace strong to red *
add default type string to enum
add possible reasons
add ClipboardButton response body

<img width="923" alt="Screenshot 2023-03-01 at 15 22 16" src="https://user-images.githubusercontent.com/112015178/222138077-a0abd5ec-d289-4e21-9b9e-8dc1ce1e3ad4.png">
<img width="909" alt="Screenshot 2023-03-01 at 15 22 50" src="https://user-images.githubusercontent.com/112015178/222138184-87339352-d6fb-462d-a6fe-8c0a2fbb608c.png">

2023-03-01 15:53 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return {type: 'object', description, properties, allOf: value.allOf};
allOf use for find ref

2023-03-02 10:37 UTC, moki requested changes

2023-03-02 10:37 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
this whole function might as well be:

```
if (value.enum) {
  return 'string';
}

return value.type
```

or

```
return value.enum ?? value.type;
```

2023-03-03 13:34 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +function getType(value: JSONSchema6): JSONSchema6['type'] {
"any" in the example is a string, not a type, it seems that the remark is not relevant

2023-03-03 13:34 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +function getType(value: JSONSchema6): JSONSchema6['type'] {
`getType  -> inferType` fixed

2023-03-03 13:38 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
enum has the type "JSONSchema6Type[] | undefined" and it has possible values for enum, not their type. The purpose of the function is to set the string value "string" if the type was not specified in the specification

```
 export type JSONSchema6Type =
    | string 
    | number
    | boolean
    | JSONSchema6Object
    | JSONSchema6Array
    | null;
```

2023-03-03 13:53 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
This function should output the value of the "type" field if it is set explicitly, substitute "type: 'string'" if it is an enum and return the original type if it is not an enum, I can write in the last return like this:
`return undefined`

It seems that in the current version it is clearer that the function will return the original type than hardcoding `undefined`

2023-03-03 14:13 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
> This function should output the value of the "type" field if it is set explicitly, substitute "type: 'string'" if it is an enum and return the original type if it is not an enum, I can write in the last return like this: `return undefined`
> 
> It seems that in the current version it is clearer that the function will return the original type than hardcoding `undefined`

is there the case of:
type being set explicitly(to value other than 'string') and enum being provided for one entity?

2023-03-03 15:24 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
> type being set explicitly(to value other than 'string')
yes

> enum being provided for one entity
I don't understand this part of the question

2023-03-03 17:41 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
> > type being set explicitly(to value other than 'string')
> 
> yes
> 
> > enum being provided for one entity
> 
> I don't understand this part of the question

do we have a case when type is being set to value other that string and enum is also provided **at the same time**

2023-03-06 01:07 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return value.type;
> do we have a case when type is being set to value other that string and enum is also provided at the same time

yes.
example#1
```
        name:
          type: integer
          enum:
            - 1
            - 2
```

Generated type:
```
export const PetNameEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
```
example#2:
```
        name:
          type: string
          enum:
            - 1
            - 2
```
Generated type:
```
export const PetNameEnum = {
    _1: '1',
    _2: '2'
} as const;
```


In the OPEN API specification, enum is always an array.
https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json#L404

I fixed the type and made the logic, if type was not passed, then type is taken from enum[0]

2023-03-06 13:12 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return required ? `${key}<span style="color: var(--yc-color-text-danger);">*</span>` : key;
fixed:
https://github.com/yandex-cloud/yfm-docs/pull/300/commits/e9461d1ecfb177d91ae7c2b13641ca5c6ac44cd3

2023-03-07 12:18 UTC, moki commented
@zorox112-practicum i can approve ui changes as they are rn, and we will move on with this PR.

if you want to finish implementation of json6schema normalization, cherry pick commits that are about it onto another separate branch -> make PR then we will continue discussion there.

don't forget to cleanup commit history tho.

2023-03-07 13:35 UTC, zorox112-practicum commented
@moki ^

2023-03-07 14:22 UTC, zorox112-practicum commented
@moki 
this is the final version, sorry ^

2023-03-09 03:19 UTC, moki commented
@zorox112-practicum 

cleanup commit history:

rebase squash:

f0ec15e8f04c51b60b807c31399f92a71af783a9 into dc051c2c3c41718ce2fce9da74d091475b8ee6e6
c78258ee796acf33d6f405e8ac9d74635825ad97 into 88e27944370734a056d210d5da0b1dea42fd06c5

give meaningful name to each commit to have clear changelogs

describe functionality that you fix/add concisely in header and optionally go in depth inside the commit body.

commit messages:

f7bde2781f1ffb5e40650ba4c947b6eeb8dd6314 i see that you set data attribute for the link element why tho i have no idea, **describe what problem you are fixing with it**

dc051c2c3c41718ce2fce9da74d091475b8ee6e6 same goes for the **replacing strong with red**

6adb8e000483d85cc759bb5d013d14f4562c2dad better commit message would be `display request failure debug information`

2023-03-09 03:24 UTC, moki commented on src/services/includers/batteries/openapi/plugin/public/components/Error.tsx
> +import {Text as TextEnum, yfmSandbox, possibleReasonsFailToFetch} from '../../constants';
i've missed the point we started declaring constants in a camelCase

you wouldn't have to do `as TextEnum` if usual convention of having constants in uppercase SNAKE_CASE were followed.

about naming `FETCH_FAILURES` would be clear enough to describe constant values and more concise.

2023-03-13 19:18 UTC, moki approved these changes

2023-03-13 19:27 UTC, merged