Add default type for enum
yandex-cloud/yfm-docs pull request #302
Opened 2023-03-07 13:07 UTC by zorox112-practicum

2023-03-09 19:54 UTC, moki requested changes

2023-03-09 19:54 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +type OpenJSONSchema = Omit<JSONSchema6, 'enum'> & {example?: any; enum?: Array<any>};
if you want to overwrite types, then construct appropriate type, exlcuding unsupported values(using exclude)

call it smth meaningful like Supported/ImplementedJSONSchema6EnumType

2023-03-09 19:54 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    if (value.enum && Array.isArray(value.enum)) {
factor it out into separate function

`isEnumOfImplementedType`/`isEnumOfSupportedType` checking if value is one of the supported types

if so return that enum type, otherwise throwing

2023-03-09 19:54 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +function inferType(value: OpenJSONSchema): JSONSchema6['type'] {
as far as i understand `inferType` might return `undefined` yet i can't find you handling that scenario

2023-03-10 01:15 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +function inferType(value: OpenJSONSchema): JSONSchema6['type'] {
This PR is about adding a type calculation for enum, this function does not handle undefined.

2023-03-10 01:15 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    if (value.enum && Array.isArray(value.enum)) {
fixed

2023-03-10 01:15 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +type OpenJSONSchema = Omit<JSONSchema6, 'enum'> & {example?: any; enum?: Array<any>};
sorry, this is deprecated code.

deleted this code

2023-03-10 01:17 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/constants.ts
> +const SUPPORTED_ENUM_TYPES = ['string', 'number'] as const;
Please keep an array here for convenient type generation.

2023-03-10 01:19 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +    return SUPPORTED_ENUM_TYPES.some((type) => enumType === type);
The includes method does not allow using TS

2023-03-10 10:32 UTC, moki commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +function inferType(value: OpenJSONSchema): JSONSchema6['type'] {
> This PR is about adding a type calculation for enum

1. you are adding function to infer type from value.

2. this function has undefined as one of its return values

3. either handle function returning undefined when you call it or throw error instead of returning undefined inside of the function.

2023-03-10 12:05 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/traverse.ts
> +function inferType(value: OpenJSONSchema): JSONSchema6['type'] {
fixed

2023-03-13 18:45 UTC, moki approved these changes

2023-03-13 18:55 UTC, merged