add view for primitive body
yandex-cloud/yfm-docs pull request #304
Opened 2023-03-08 23:34 UTC by zorox112-practicum

2023-03-09 19:24 UTC, moki requested changes

2023-03-09 19:24 UTC, moki commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +function isPrimitive(type: JSONSchema6['type']) {
> `const primitives: Array<JSONSchema6['type']> = ['string', 'boolean', 'null', 'number', 'integer'];`

make it a Set of values

```
const PRIMITIVE_JSON6_SCHEMA_TYPES = new Set<PrimitiveJSONSchema6TypeName>(['string', 'boolean', 'null', 'number', 'integer']);
```

```
import {PRIMITIVE_JSON6_SCHEMA_TYPES} from ..

function isPrimitive(type: .. ) {
    return PRIMITIVE_JSON6_SCHEMA_TYPES.has(type);
}
```

factor it out into separate constants file, there is no reason to create a constant every time function gets called

---

if you want to type it, do it using exclude:

```
type JSONSchema6TypeName =
    | 'string'
    | 'number'
    | 'integer'
    | 'boolean'
    | 'object'
    | 'array'
    | 'null'
    | 'any';

type PrimitiveJSONSchema6TypeName = Exclude<JSONSchema6TypeName, 'object' | 'array'>;

type ComplexJSONSchema6TypeName = Exclude<JSONSchema6TypeName, primitiveJSONSchema6TypeName>;
```

`isPrimitive` function should follow `openapiBody` function, file should be read from abstracts into specifics.(move `isPrimitive` after `openapiBody`)

2023-03-09 19:24 UTC, moki commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    if (isPrimitive(schema.type)) {
examine the code that goes ahead:
https://github.com/yandex-cloud/yfm-docs/blob/dcbfa495a65c7535fcf6fab6f9e47f7530bf0d41/src/services/includers/batteries/openapi/generators/endpoint.ts#L204

```
const result = [
    block([
        title(4)('Body'),
        cut(code(stringify(parsedSchema, null, 4)), type),
        content,
    ]),
];
```

there is `result` array that gets filled with parsed values and then rendered

hoist it up initialiazed with common values ie `title(4)('Body')`

and then in case of type being primitive fill it up accordingly and return early

2023-03-09 23:59 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +function isPrimitive(type: JSONSchema6['type']) {
fixed

The new type was not needed

2023-03-10 01:25 UTC, zorox112-practicum commented on src/services/includers/batteries/openapi/generators/endpoint.ts
> +    if (isPrimitive(schema.type)) {
up `title(4)('Body')`

I didn't understand about the result, is this option offered?
```
function openapiBody(allRefs: Refs, pagePrintedRefs: Set<string>, obj?: Schema) {
    if (!obj) {
        return '';
    }

    const {type = 'schema', schema} = obj;
    const sectionTitle = title(4)('Body');
    const result = [];

    if (isPrimitive(schema.type)) {
        result.push(
            sectionTitle,
            type,
            `${bold('Type:')} ${schema.type}`,
            Boolean(schema.format) && `${bold('Format:')} ${schema.format}`,
            Boolean(schema.description) && `${bold('Description:')} ${schema.description}`,
        );
        return block(result);
    }

    const {content, tableRefs} = tableFromSchema(allRefs, schema);
    const parsedSchema = prepareSampleObject(schema);

    result.push(
        block([
            sectionTitle,
            cut(code(stringify(parsedSchema, null, 4)), type),
            content,
        ]),
    );

    // print all dependent objects to separate tables recursively
    result.push(...printAllTables(allRefs, pagePrintedRefs, tableRefs));

    return block(result);
}
```

or second option:
```
function openapiBody(allRefs: Refs, pagePrintedRefs: Set<string>, obj?: Schema) {
    if (!obj) {
        return '';
    }

    const {type = 'schema', schema} = obj;
    const sectionTitle = title(4)('Body');
    const result = [];

    if (isPrimitive(schema.type)) {
        result.push(
            sectionTitle,
            type,
            `${bold('Type:')} ${schema.type}`,
            Boolean(schema.format) && `${bold('Format:')} ${schema.format}`,
            Boolean(schema.description) && `${bold('Description:')} ${schema.description}`,
        );
    } else {
        const {content, tableRefs} = tableFromSchema(allRefs, schema);
        const parsedSchema = prepareSampleObject(schema);

        result.push(
            block([
                sectionTitle,
                cut(code(stringify(parsedSchema, null, 4)), type),
                content,
            ]),
        );

        // print all dependent objects to separate tables recursively
        result.push(...printAllTables(allRefs, pagePrintedRefs, tableRefs));
    }

    return block(result);
}
```

2023-03-13 18:44 UTC, moki approved these changes

2023-03-13 19:08 UTC, merged