feat: get file author from github
yandex-cloud/yfm-docs pull request #312
Opened 2023-03-16 11:29 UTC by niktverd

2023-03-16 11:30 UTC, niktverd commented
manually added
---
author: {'avatar':'https://avatars.githubusercontent.com/u/43607074?v=4','email':'alehaymkm@gmail.com','login':'alehay','name':'Aleksei Kudakov','url':'https://github.com/alehay'}
__system: {"dislikeVariants":["Нет ответа на мой вопрос","Рекомендации не помогли","Содержание не соответствует заголовку","Другое"]}
contributors: [{'avatar':'https://avatars.githubusercontent.com/u/43607074?v=4','email':'alehaymkm@gmail.com','login':'alehay','name':'Aleksei Kudakov','url':'https://github.com/alehay','date':'2021-11-16T09:31:43Z'}]
---

automatically added
---
__system: {"dislikeVariants":["Нет ответа на мой вопрос","Рекомендации не помогли","Содержание не соответствует заголовку","Другое"]}

author: {'avatar':'https://avatars.githubusercontent.com/u/56478986?v=4','email':'56478986+gayratvg@users.noreply.github.com','login':'gayratvg','name':'Gayrat Vlasov_2','url':'https://github.com/gayratvg','date':'2022-02-21T09:55:38Z'}
contributors: [{'avatar':'https://avatars.githubusercontent.com/u/56478986?v=4','email':'56478986+gayratvg@users.noreply.github.com','login':'gayratvg','name':'Gayrat Vlasov_2','url':'https://github.com/gayratvg','date':'2022-02-21T09:55:38Z'}]
---

2023-03-23 09:53 UTC, moki requested changes

2023-03-23 09:53 UTC, moki commented on src/vcs-connector/github.ts
> +    console.log({author: commit.author});
unnecessary logging

2023-03-23 09:53 UTC, moki commented on src/services/utils.ts
> +        } catch (_) {}
proper error handling is missing

2023-03-23 09:53 UTC, moki commented on src/vcs-connector/github.ts
> +        const newContributorKey = Object.keys(newContributor)[0];
is it impossible for a `newContributor` object to be empty?

2023-03-23 09:59 UTC, moki commented on src/services/authors.ts
> +            return `${fileMetadata}${os.EOL}author: ${user}`;
you don't want to use os.EOL (os specific symbols) if your code will run on one system, and then write data for later to be used somewhere in the other system with different os.

use os agnostic new line symbol

2023-03-24 04:58 UTC, niktverd commented on src/vcs-connector/github.ts
> +    console.log({author: commit.author});
exactly

2023-03-24 05:00 UTC, niktverd commented on src/services/utils.ts
> +        } catch (_) {}
sure

2023-03-24 05:05 UTC, niktverd commented on src/vcs-connector/github.ts
> +        const newContributorKey = Object.keys(newContributor)[0];
Looks likes it cannot be empty. But let's add an additional check

2023-03-24 05:13 UTC, niktverd commented on src/services/authors.ts
> +            return `${fileMetadata}${os.EOL}author: ${user}`;
We already had a talk in a private chat. Shortly, running on `Windows` already inserts `os specific symbol`. Adding os.EOL helps to maintain sameness

2023-03-24 13:23 UTC, moki commented on src/services/utils.ts
> +        } catch (_) {}
please use [logger module](https://github.com/yandex-cloud/yfm-docs/blob/master/src/utils/logger.ts)

warn for `non fatal` errors and `error` for fatal ones.

2023-03-24 13:29 UTC, moki commented on src/services/utils.ts
> +            console.error(err);
please use [logger module](https://github.com/yandex-cloud/yfm-docs/blob/master/src/utils/logger.ts)

warn for `non fatal` errors and `error` for fatal ones.

2023-03-24 13:33 UTC, moki commented on src/services/utils.ts
> +export function getContributorArrayFromMetadata(metadata: string[]) {
also thinking about it – i don't think this is utility function, looks more like authors service buisness logic.

2023-03-27 09:40 UTC, niktverd commented on src/services/utils.ts
> +export function getContributorArrayFromMetadata(metadata: string[]) {
moved

2023-03-27 09:41 UTC, niktverd commented on src/services/utils.ts
> +            console.error(err);
ok

2023-03-28 10:18 UTC, moki approved these changes

2023-03-28 10:19 UTC, merged