feat(authors): collect authors from github
yandex-cloud/yfm-docs pull request #355
Opened 2023-05-26 18:06 UTC by niktverd

2023-05-29 17:41 UTC, Feverqwe commented on src/vcs-connector/github.ts
> +        const getAuthorCommand = `git log --pretty=format:"%ae;%H" --follow -- ${path} | tail -n 1`;
I think it will not work on windows platform

2023-05-31 10:13 UTC, niktverd commented on src/vcs-connector/github.ts
> +        const getAuthorCommand = `git log --pretty=format:"%ae;%H" --follow -- ${path} | tail -n 1`;
Fixed

2023-05-31 10:50 UTC, Feverqwe commented
If we are using `execa`, maybe replace other calls `execAsync` to `execa`, I see it only two? And then we could remove `execAsync`.

2023-05-31 10:51 UTC, Feverqwe commented
In general looks fine.

2023-05-31 10:53 UTC, Feverqwe commented on src/vcs-connector/github.ts
> +        const userData = dataArray[0];
U can use .shift, and don't do splice(1) on the next to line.

2023-05-31 10:56 UTC, Feverqwe commented on src/vcs-connector/github.ts
> +            const repoCommit = await github.getRepoCommitByHash(httpClientByToken, hashCommit);
How many api call we are doing, could we reach api rate limits?

2023-05-31 11:47 UTC, moki requested changes

2023-05-31 11:47 UTC, moki commented on package.json
> +    "execa": "^5.1.1",
we already have shelljs to execute commands

https://github.com/yandex-cloud/yfm-docs/blob/449516ad1f1f48d96ee18feaa0b9f81ba83403c2/package.json#L60

2023-05-31 11:47 UTC, moki commented on src/vcs-connector/github.ts
> +        if (!email.includes('@yandex-team.ru')) {
this can't be hardcoded

2023-05-31 11:47 UTC, moki commented on src/vcs-connector/github.ts
> +            const repoCommit = await github.getRepoCommitByHash(httpClientByToken, hashCommit);
if you are gonna limit concurrency, we have https://github.com/yandex-cloud/yfm-docs/blob/449516ad1f1f48d96ee18feaa0b9f81ba83403c2/package.json#L45 for granulated concurrency

2023-05-31 11:51 UTC, moki commented on src/vcs-connector/github.ts
> +    for (const path of paths) {
> I think we could do some checks in parallel, using p-map for example with some concurrency. But then need do calls to the api in the next step.

if you are gonna limit concurrency, we have https://github.com/yandex-cloud/yfm-docs/blob/449516ad1f1f48d96ee18feaa0b9f81ba83403c2/package.json#L45 for granular concurrency

2023-05-31 12:57 UTC, niktverd commented on src/vcs-connector/github.ts
> +            const repoCommit = await github.getRepoCommitByHash(httpClientByToken, hashCommit);
up to 20 

`User access token requests are limited to 5,000 requests per hour and per authenticated user. `

2023-05-31 16:12 UTC, niktverd commented on package.json
> +    "execa": "^5.1.1",
@Feverqwe require to pass all the parameters as an array of arguments to `git`
`shell.exec()`  can get only a raw string. @Feverqwe says that passing raw string is not safe.

That is the reason why I added new package. We already use it in `yfm-server`, for example

2023-05-31 17:49 UTC, moki commented on package.json
> +    "execa": "^5.1.1",
@niktverd we are not adding another dependency to execute commands just because you are using this package already somewhere else

apparently we also have git sdk

https://github.com/yandex-cloud/yfm-docs/blob/a04cf141d83b5ad8acf46de03f8047df0f0d030c/package.json#LL61C6-L61C16

check out if it fits your use case

2023-06-01 15:43 UTC, moki requested changes

2023-06-02 06:17 UTC, niktverd commented on src/vcs-connector/github.ts
> +        if (email === 'robot-dataui-vcs@yandex-team.ru') {
fix

2023-06-07 11:30 UTC, moki commented on src/vcs-connector/github.ts
> +    const externalCommits = (await mapLimit(paths, MAX_CONCURRENCY, async (path: string) => {
this is weird, factor out mapLimit cb into separate function

2023-06-08 10:42 UTC, moki requested changes

2023-06-08 11:31 UTC, moki commented
@niktverd 

LGTM

but u've added package-lock.json even tho you didn't change any dependencies

i'll find time to resolve conflicts and merge it later today.

2023-06-08 17:45 UTC, merged