fix: asyncify mapLimit callback, authorByGitEmail map added to reduce api request to GitHub
yandex-cloud/yfm-docs pull request #465
Opened 2023-06-29 17:53 UTC by niktverd

2023-07-03 10:38 UTC, Feverqwe approved these changes
Looks good

2023-07-06 09:47 UTC, moki commented on src/vcs-connector/github.ts
> +const ignoreAuthor = process.env.IGNORE_AUTHOR;
why are you taking ignoreAuthor out of env variables instead of config file?

2023-07-06 09:59 UTC, moki requested changes

2023-07-06 09:59 UTC, moki commented on src/vcs-connector/github.ts
> +const ignoreAuthor = process.env.IGNORE_AUTHOR;
yeah, i think since this is not smth like credentials(auth tokens etc), we should specify it inside the config file.

putting smth like this in env variables "hides" it.

imagine someone would need "ignoreAuthor" parameter in other completely different context, overriding this one without even knowing it exists.

2023-07-06 10:41 UTC, niktverd commented on src/vcs-connector/github.ts
> +const ignoreAuthor = process.env.IGNORE_AUTHOR;
@Feverqwe asked to change this point

2023-07-06 10:47 UTC, Feverqwe commented on src/vcs-connector/github.ts
> +const ignoreAuthor = process.env.IGNORE_AUTHOR;
@moki it looks like internal case, so we don't add it in flags.

2023-07-06 11:11 UTC, moki commented on src/vcs-connector/github.ts
> +const ignoreAuthor = process.env.IGNORE_AUTHOR;
> @moki it looks like internal case, so we don't add it in flags.

read in my other comment, why its a bad idea.

2023-07-06 11:14 UTC, niktverd commented on src/vcs-connector/github.ts
> +const ignoreAuthor = process.env.IGNORE_AUTHOR;
I got your point. I will return it back soon

2023-07-07 12:57 UTC, moki approved these changes
LGTM

2023-07-07 13:00 UTC, merged