feat: ignore contributors if an email includes string from the --ignore-author parameter
yandex-cloud/yfm-docs pull request #504
Opened 2023-07-17 16:54 UTC by niktverd

2023-07-17 17:10 UTC, Feverqwe approved these changes
Looks good

2023-07-17 17:12 UTC, Feverqwe commented on src/vcs-connector/github.ts
> +        if (email.includes(ignoreAuthor)) {
ignoreAuthor should not be empty

2023-07-17 17:31 UTC, Feverqwe approved these changes

2023-07-17 19:29 UTC, moki approved these changes

2023-07-17 19:36 UTC, moki requested changes
I am just gonna point out that `email.includes(ignoreAuthor)` might exclude more than one originally intended.

let's say that we have user `gma` that we want to ignore.

the check `email.includes(ignoreAuthor)` will exclude all of the emails with the domain `@gmail.com`.

so, yeah... doesn't sound like a good filtering to me.

@3y3 wanna share you opinion on this?

@niktverd correct me if i misunderstood, but i just noticed this and it's like, well... really bad.

2023-07-18 05:56 UTC, niktverd commented on src/vcs-connector/github.ts
> +        if (email.includes(ignoreAuthor)) {
fixed

2023-07-18 08:39 UTC, 3y3 approved these changes

2023-07-19 09:42 UTC, moki requested changes

2023-07-19 09:42 UTC, moki commented on src/vcs-connector/github.ts
> +    const {ignoreAuthor} = ArgvService.getConfig();
if `ignoreAuthor` becomes becomes collection of patterns that will be matched against, i think the name should reflect it.

how about calling it `ignoreAuthorPatterns`?

2023-07-19 09:42 UTC, moki commented on src/vcs-connector/github.ts
> +    const emailPatterns = ignoreAuthor.split(',');
correct me if i am wrong, but glob expressions can contain commas(`,`), therefore this will lead to splitting some of the expressions containing them, leading to undefined behaviour.

2023-07-19 11:50 UTC, moki approved these changes
lgtm

2023-07-19 12:35 UTC, niktverd commented on src/vcs-connector/github.ts
> +    const {ignoreAuthor} = ArgvService.getConfig();
Good point. Done

2023-07-19 12:35 UTC, niktverd commented on src/vcs-connector/github.ts
> +    const emailPatterns = ignoreAuthor.split(',');
Good point, I have rearranged input option and made it an array

2023-07-19 13:11 UTC, 3y3 approved these changes

2023-07-19 14:04 UTC, merged