feat: change a log level while a request to github failed because a commit not found
yandex-cloud/yfm-docs pull request #505
Opened 2023-07-17 16:58 UTC by niktverd

…ot found

2023-07-17 17:49 UTC, 3y3 requested changes

2023-07-17 17:49 UTC, 3y3 commented on src/vcs-connector/client/github.ts
> +import {GraphqlResponseError} from '@octokit/graphql';
This dependency in not installed in project

2023-07-17 17:49 UTC, 3y3 commented on src/vcs-connector/client/github.ts
> +        if ((error as GraphqlResponseError<{message: string}>)?.response?.data?.message?.includes(
Is there more precise class for `instanceof` check?

2023-07-17 19:18 UTC, niktverd commented on src/vcs-connector/client/github.ts
> +import {GraphqlResponseError} from '@octokit/graphql';
Removed it and replaced with custom class

2023-07-17 19:20 UTC, niktverd commented on src/vcs-connector/client/github.ts
> +        if ((error as GraphqlResponseError<{message: string}>)?.response?.data?.message?.includes(
Replaced it with custom class. Error Type in @octokit made confused way

2023-07-19 14:03 UTC, 3y3 requested changes

2023-07-19 14:03 UTC, 3y3 commented on src/vcs-connector/client/github.ts
> +class ResponseError extends Error {
I don't see where this class will be instantiated.
Should it be a Type?

2023-07-21 11:57 UTC, 3y3 approved these changes

2023-07-21 11:58 UTC, merged