Add contributors on docs pages
yandex-cloud/yfm-docs pull request #54
Opened 2021-03-22 09:20 UTC by nanov94

2021-04-01 08:22 UTC, vovcyan requested changes

2021-04-01 08:22 UTC, vovcyan commented on src/client/github.ts
> +    const repo = REPO || yfmConfig.repo || '';
Same

Плюс думаю будет полезным добавить валидацию на пустую строку, чтобы не падать с неизвестными ошибками от `octokit`

2021-04-01 08:22 UTC, vovcyan commented on src/client/github.ts
> +    const match = email.match(regexpLogin);
Могу ошибаться, то `.split('@')` выглядит проще

2021-04-01 08:22 UTC, vovcyan commented on src/client/github.ts
> +    const match = email.match(regexpLogin);
При том, к сожалению, github login может отличаться email

2021-04-01 08:22 UTC, vovcyan commented on src/client/models.ts
> +    github = 'github',
CamelCase ?

2021-04-01 15:34 UTC, nanov94 commented on src/client/models.ts
> +/* eslint-disable camelcase */
думаешь все таки 1 оставить?

2021-04-02 10:11 UTC, vovcyan requested changes

2021-04-02 10:11 UTC, vovcyan commented on webpack.config.js
> +                            plugins: ['@babel/plugin-transform-runtime', '@babel/plugin-syntax-top-level-await'],
Для этого есть специальный файл .babellrc. Давай вынесем туда?

2021-04-02 10:11 UTC, vovcyan commented on src/client/models.ts
> +    arcanum = 'arcanum',
CamelCase

Github
Bitbucket
Arcanum ?

2021-04-02 10:11 UTC, vovcyan commented on src/client/client.ts
> +function getYfmConfig(pathToYfmConfig: string): YfmConfig {
В argvValidator необходимо описать логику что есть пользователь указал contributors: true, а у него при этом нет ни одного коннектора, необходимо сообщить об этом ошибкой

2021-04-02 10:11 UTC, vovcyan commented on src/client/client.ts
> +function getYfmConfig(pathToYfmConfig: string): YfmConfig {
Получать/парсить yfm конфиг дважды нет необходимости, так как его можно получить в любом месте

2021-04-02 10:11 UTC, vovcyan commented on src/client/client.ts
> +async function getGithubContributorsByPathFunction(rootPath: string, client: RepoClient, options: ClientOptions): Promise<ContributorsFunction> {
Договорились что этим будет заниматься connector. Вызываем connector с пераданными параметрами, а он возвращает массив c Contributors

2021-04-02 10:11 UTC, vovcyan commented on src/client/github.ts
> +        log.error(`Getting contributors was failed. Error: ${JSON.stringify(error)}`);
Getting of contributors has been failed

2021-04-02 10:50 UTC, nanov94 commented on src/client/models.ts
> +    arcanum = 'arcanum',
тогда это `PascalCase`, потому что `camelCase` <- такой вид
думаю тут тогда лучше все upercase, поскольку enum

2021-04-02 10:50 UTC, nanov94 commented on src/client/models.ts
> +/* eslint-disable camelcase */
ну хз, лучше заранее предусмотреть, сэкономить работу другим)

2021-04-02 10:50 UTC, nanov94 commented on src/index.ts
> +    const client = await getClient(_yargs.argv.input, pathToConfig, options);
я сделала это здесь поскольку в него мы прокидываем инфу о yfm конфиге, чтобы не прокидывать это в processPages. Этот комент зависит от другого, так что возможно это переедет в другое место

2021-04-05 07:09 UTC, nanov94 commented on src/client/client.ts
> +async function getGithubContributorsByPathFunction(rootPath: string, client: RepoClient, options: ClientOptions): Promise<ContributorsFunction> {
Да все так и есть `getGithubContributors` как раз возвращает всех нужных контрибьюторов.
Или ты в принципе предлагаешь перенести этот метод в github.ts?

2021-04-06 15:00 UTC, vovcyan requested changes

2021-04-06 15:00 UTC, vovcyan commented on src/vcsConnector/models.ts
> +export interface YfmConfig {
VcsConnectorConfig ?

2021-04-06 15:03 UTC, vovcyan commented on src/index.ts
> +dotEnv.config({path: dotEnvPath});
Обсудили offline что нет необходимости в том чтобы брать данные из .env

2021-04-07 07:10 UTC, vovcyan requested changes

2021-04-07 07:10 UTC, vovcyan commented on src/models.ts
> +    connector?: VCSConnectorConfig;
Поле connector мы передаем только через YfmConfig. Стоит перенести в интерфейс выше

2021-04-07 07:10 UTC, vovcyan commented on src/utils.ts
> +    return meta;
return Object.entries().map(([name, content]) => {...}).join('\n') ?

2021-04-07 07:20 UTC, vovcyan requested changes

2021-04-07 07:20 UTC, vovcyan commented on src/steps/processPages.ts
> +                tmpInputfilePath: pathData.resolvedPathToFile,
tmpInputFilePath ?

2021-04-07 07:25 UTC, vovcyan commented on src/vcs-connector/index.ts
> +            return;
Думаю что более честно было бы возвращать здесь null

2021-04-08 07:41 UTC, vovcyan commented on src/vcs-connector/github.ts
> +        log.warn('Invalid token or endpoint');
GitHub Token and API endpoint must be provided

2021-04-08 13:50 UTC, vovcyan commented on src/vcs-connector/github.ts
> +        log.warn(getMsgСonfigurationMustBeProvided(SourceType.GITHUB));
return [] ?

2021-04-08 13:55 UTC, vovcyan requested changes

2021-04-08 13:55 UTC, vovcyan commented on src/vcs-connector/index.ts
> +    const connectorType = process.env.VCS_CONNECTOR_TYPE || connector && connector.type || '';
На мой взгляд значение в виде пустой строки ни на что не влияет и его можно убрать

2021-04-08 13:55 UTC, vovcyan commented on src/constants.ts
> +    (repo: string) => `Сonfiguration must be provided for ${repo} like env variable or in .yfm file`;
Лучше всего оставить рядом connector'ом, так как больше это довольно специфичный кейс и он больше нигде не используется

2021-04-09 07:22 UTC, vovcyan approved these changes

2021-04-09 09:49 UTC, nanov94 commented on src/constants.ts
> +    (repo: string) => `Сonfiguration must be provided for ${repo} like env variable or in .yfm file`;
move to another PR

2021-04-09 09:49 UTC, merged